/**
 * The screens' own icon exports, pulled from the Figma file itself.
 *
 * `download_assets` returns asset URLs on www.figma.com, which this environment's
 * network policy blocks — so these came out through the plugin API instead
 * (`node.exportAsync({ format: 'SVG' })`), which travels the MCP channel. Each one
 * is exported from the INSTANCE rather than the component, so it carries the colour
 * the design actually applies at that call site rather than the component's
 * uncoloured black.
 *
 * Intrinsic sizes below are read from each file's own root attributes. Do not
 * override them at a call site: the root width/height is the asset's real size, and
 * forcing a different aspect ratio distorts the glyph.
 *
 * GENERATED by scripts/gen-icons.mjs — re-run it after adding an .svg here.
 */
import add_one from './add-one.svg';
import battery from './battery.svg';
import cart from './cart.svg';
import cellular_connection from './cellular-connection.svg';
import chevron_right from './chevron-right.svg';
import dots_horizontal from './dots-horizontal.svg';
import ellipse_79 from './ellipse-79.svg';
import filter_lines from './filter-lines.svg';
import grid_01 from './grid-01.svg';
import menu_01 from './menu-01.svg';
import minus from './minus.svg';
import plus from './plus.svg';
import plus_circle from './plus-circle.svg';
import search_sm from './search-sm.svg';
import shopping_cart_01 from './shopping-cart-01.svg';
import trash_03 from './trash-03.svg';
import user_02 from './user-02.svg';
import users_02 from './users-02.svg';
import wifi from './wifi.svg';
import x_circle from './x-circle.svg';
import x_close from './x-close.svg';

export type IconName =
  | 'add-one'
  | 'battery'
  | 'cart'
  | 'cellular-connection'
  | 'chevron-right'
  | 'dots-horizontal'
  | 'ellipse-79'
  | 'filter-lines'
  | 'grid-01'
  | 'menu-01'
  | 'minus'
  | 'plus'
  | 'plus-circle'
  | 'search-sm'
  | 'shopping-cart-01'
  | 'trash-03'
  | 'user-02'
  | 'users-02'
  | 'wifi'
  | 'x-circle'
  | 'x-close';

export const ICONS: Record<IconName, { src: string; width: number; height: number }> = {
  'add-one': { src: add_one, width: 20, height: 20 },
  'battery': { src: battery, width: 28, height: 13 },
  'cart': { src: cart, width: 19, height: 18 },
  'cellular-connection': { src: cellular_connection, width: 20, height: 13 },
  'chevron-right': { src: chevron_right, width: 16, height: 16 },
  'dots-horizontal': { src: dots_horizontal, width: 20, height: 20 },
  'ellipse-79': { src: ellipse_79, width: 3, height: 3 },
  'filter-lines': { src: filter_lines, width: 16, height: 16 },
  'grid-01': { src: grid_01, width: 20, height: 20 },
  'menu-01': { src: menu_01, width: 20, height: 20 },
  'minus': { src: minus, width: 16, height: 16 },
  'plus': { src: plus, width: 16, height: 16 },
  'plus-circle': { src: plus_circle, width: 24, height: 24 },
  'search-sm': { src: search_sm, width: 20, height: 20 },
  'shopping-cart-01': { src: shopping_cart_01, width: 16, height: 16 },
  'trash-03': { src: trash_03, width: 20, height: 20 },
  'user-02': { src: user_02, width: 16, height: 16 },
  'users-02': { src: users_02, width: 40, height: 40 },
  'wifi': { src: wifi, width: 18, height: 13 },
  'x-circle': { src: x_circle, width: 20, height: 20 },
  'x-close': { src: x_close, width: 20, height: 20 },
};
