/**
 * The screens' own icon exports, pulled from the Figma file itself.
 *
 * `download_assets` returns asset URLs on www.figma.com, which this environment's
 * network policy blocks — so these came out through the plugin API instead
 * (`node.exportAsync({ format: 'SVG' })`), which travels the MCP channel. Each one
 * is exported from the INSTANCE rather than the component, so it carries the colour
 * the design actually applies at that call site rather than the component's
 * uncoloured black.
 *
 * Intrinsic sizes below are read from each file's own root attributes. Do not
 * override them at a call site: the root width/height is the asset's real size, and
 * forcing a different aspect ratio distorts the glyph.
 *
 * GENERATED by scripts/gen-icons.mjs — re-run it after adding an .svg here.
 */
import add_one from './add-one.svg';
import bank from './bank.svg';
import bank_note_02 from './bank-note-02.svg';
import cart from './cart.svg';
import check from './check.svg';
import check_24 from './check-24.svg';
import check_circle from './check-circle.svg';
import check_selected from './check-selected.svg';
import check_success from './check-success.svg';
import chevron_down from './chevron-down.svg';
import chevron_right from './chevron-right.svg';
import chevron_right_subtle from './chevron-right-subtle.svg';
import clock from './clock.svg';
import credit_card_02 from './credit-card-02.svg';
import dot_2 from './dot-2.svg';
import dots_horizontal from './dots-horizontal.svg';
import dots_horizontal_24 from './dots-horizontal-24.svg';
import ellipse_79 from './ellipse-79.svg';
import expand_01 from './expand-01.svg';
import facebook from './facebook.svg';
import filter_lines from './filter-lines.svg';
import gift_02 from './gift-02.svg';
import grid_01 from './grid-01.svg';
import instagram from './instagram.svg';
import layout_alt_02 from './layout-alt-02.svg';
import list from './list.svg';
import menu_01 from './menu-01.svg';
import minus from './minus.svg';
import minus_lg from './minus-lg.svg';
import percent_03 from './percent-03.svg';
import plus from './plus.svg';
import plus_circle from './plus-circle.svg';
import plus_lg from './plus-lg.svg';
import printer from './printer.svg';
import rows_03 from './rows-03.svg';
import scan from './scan.svg';
import scan_line from './scan-line.svg';
import search_sm from './search-sm.svg';
import share_01 from './share-01.svg';
import shopping_cart_01 from './shopping-cart-01.svg';
import shopping_cart_40 from './shopping-cart-40.svg';
import tiktok from './tiktok.svg';
import toast_check_card from './toast-check-card.svg';
import toast_success from './toast-success.svg';
import trash_01 from './trash-01.svg';
import trash_03 from './trash-03.svg';
import trash_03_danger from './trash-03-danger.svg';
import trash_03_subtle from './trash-03-subtle.svg';
import twitter from './twitter.svg';
import user_02 from './user-02.svg';
import user_02_brand from './user-02-brand.svg';
import users_02 from './users-02.svg';
import wallet_04 from './wallet-04.svg';
import x_circle from './x-circle.svg';
import x_close from './x-close.svg';
import x_close_camera from './x-close-camera.svg';

export type IconName =
  | 'add-one'
  | 'bank'
  | 'bank-note-02'
  | 'cart'
  | 'check'
  | 'check-24'
  | 'check-circle'
  | 'check-selected'
  | 'check-success'
  | 'chevron-down'
  | 'chevron-right'
  | 'chevron-right-subtle'
  | 'clock'
  | 'credit-card-02'
  | 'dot-2'
  | 'dots-horizontal'
  | 'dots-horizontal-24'
  | 'ellipse-79'
  | 'expand-01'
  | 'facebook'
  | 'filter-lines'
  | 'gift-02'
  | 'grid-01'
  | 'instagram'
  | 'layout-alt-02'
  | 'list'
  | 'menu-01'
  | 'minus'
  | 'minus-lg'
  | 'percent-03'
  | 'plus'
  | 'plus-circle'
  | 'plus-lg'
  | 'printer'
  | 'rows-03'
  | 'scan'
  | 'scan-line'
  | 'search-sm'
  | 'share-01'
  | 'shopping-cart-01'
  | 'shopping-cart-40'
  | 'tiktok'
  | 'toast-check-card'
  | 'toast-success'
  | 'trash-01'
  | 'trash-03'
  | 'trash-03-danger'
  | 'trash-03-subtle'
  | 'twitter'
  | 'user-02'
  | 'user-02-brand'
  | 'users-02'
  | 'wallet-04'
  | 'x-circle'
  | 'x-close'
  | 'x-close-camera';

export const ICONS: Record<IconName, { src: string; width: number; height: number }> = {
  'add-one': { src: add_one, width: 20, height: 20 },
  'bank': { src: bank, width: 20, height: 20 },
  'bank-note-02': { src: bank_note_02, width: 20, height: 20 },
  'cart': { src: cart, width: 19, height: 18 },
  'check': { src: check, width: 20, height: 20 },
  'check-24': { src: check_24, width: 24, height: 24 },
  'check-circle': { src: check_circle, width: 48, height: 48 },
  'check-selected': { src: check_selected, width: 20, height: 20 },
  'check-success': { src: check_success, width: 40, height: 40 },
  'chevron-down': { src: chevron_down, width: 20, height: 20 },
  'chevron-right': { src: chevron_right, width: 16, height: 16 },
  'chevron-right-subtle': { src: chevron_right_subtle, width: 20, height: 20 },
  'clock': { src: clock, width: 16, height: 16 },
  'credit-card-02': { src: credit_card_02, width: 20, height: 20 },
  'dot-2': { src: dot_2, width: 2, height: 2 },
  'dots-horizontal': { src: dots_horizontal, width: 20, height: 20 },
  'dots-horizontal-24': { src: dots_horizontal_24, width: 24, height: 24 },
  'ellipse-79': { src: ellipse_79, width: 3, height: 3 },
  'expand-01': { src: expand_01, width: 20, height: 20 },
  'facebook': { src: facebook, width: 15.316, height: 15.316 },
  'filter-lines': { src: filter_lines, width: 16, height: 16 },
  'gift-02': { src: gift_02, width: 20, height: 20 },
  'grid-01': { src: grid_01, width: 20, height: 20 },
  'instagram': { src: instagram, width: 15.316, height: 15.316 },
  'layout-alt-02': { src: layout_alt_02, width: 40, height: 40 },
  'list': { src: list, width: 20, height: 20 },
  'menu-01': { src: menu_01, width: 20, height: 20 },
  'minus': { src: minus, width: 16, height: 16 },
  'minus-lg': { src: minus_lg, width: 32, height: 32 },
  'percent-03': { src: percent_03, width: 20, height: 20 },
  'plus': { src: plus, width: 16, height: 16 },
  'plus-circle': { src: plus_circle, width: 24, height: 24 },
  'plus-lg': { src: plus_lg, width: 32, height: 32 },
  'printer': { src: printer, width: 16, height: 16 },
  'rows-03': { src: rows_03, width: 20, height: 20 },
  'scan': { src: scan, width: 28, height: 28 },
  'scan-line': { src: scan_line, width: 274, height: 3 },
  'search-sm': { src: search_sm, width: 20, height: 20 },
  'share-01': { src: share_01, width: 16, height: 16 },
  'shopping-cart-01': { src: shopping_cart_01, width: 16, height: 16 },
  'shopping-cart-40': { src: shopping_cart_40, width: 40, height: 40 },
  'tiktok': { src: tiktok, width: 15.316, height: 15.316 },
  'toast-check-card': { src: toast_check_card, width: 20, height: 20 },
  'toast-success': { src: toast_success, width: 20, height: 20 },
  'trash-01': { src: trash_01, width: 20, height: 20 },
  'trash-03': { src: trash_03, width: 20, height: 20 },
  'trash-03-danger': { src: trash_03_danger, width: 16, height: 16 },
  'trash-03-subtle': { src: trash_03_subtle, width: 20, height: 20 },
  'twitter': { src: twitter, width: 13.08, height: 13.08 },
  'user-02': { src: user_02, width: 16, height: 16 },
  'user-02-brand': { src: user_02_brand, width: 20, height: 20 },
  'users-02': { src: users_02, width: 40, height: 40 },
  'wallet-04': { src: wallet_04, width: 20, height: 20 },
  'x-circle': { src: x_circle, width: 20, height: 20 },
  'x-close': { src: x_close, width: 20, height: 20 },
  'x-close-camera': { src: x_close_camera, width: 20, height: 20 },
};
