/**
 * Regenerates src/assets/icons/index.ts from the .svg files beside it, reading each
 * one's intrinsic size from its own root attributes rather than a hand-kept list.
 */
import fs from 'node:fs';
import path from 'node:path';

const dir = path.join(import.meta.dirname, '..', 'src', 'assets', 'icons');
const names = fs.readdirSync(dir).filter((f) => f.endsWith('.svg')).map((f) => f.replace(/\.svg$/, '')).sort();
const ident = (n) => n.replace(/[^a-zA-Z0-9]/g, '_');

const sizes = Object.fromEntries(names.map((n) => {
  const svg = fs.readFileSync(path.join(dir, `${n}.svg`), 'utf8');
  const w = svg.match(/<svg[^>]*\swidth="([\d.]+)"/)?.[1];
  const h = svg.match(/<svg[^>]*\sheight="([\d.]+)"/)?.[1];
  if (!w || !h) throw new Error(`${n}.svg has no root width/height`);
  return [n, [w, h]];
}));

const out = `/**
 * The screens' own icon exports, pulled from the Figma file itself.
 *
 * \`download_assets\` returns asset URLs on www.figma.com, which this environment's
 * network policy blocks — so these came out through the plugin API instead
 * (\`node.exportAsync({ format: 'SVG' })\`), which travels the MCP channel. Each one
 * is exported from the INSTANCE rather than the component, so it carries the colour
 * the design actually applies at that call site rather than the component's
 * uncoloured black.
 *
 * Intrinsic sizes below are read from each file's own root attributes. Do not
 * override them at a call site: the root width/height is the asset's real size, and
 * forcing a different aspect ratio distorts the glyph.
 *
 * GENERATED by scripts/gen-icons.mjs — re-run it after adding an .svg here.
 */
${names.map((n) => `import ${ident(n)} from './${n}.svg';`).join('\n')}

export type IconName =
${names.map((n) => `  | '${n}'`).join('\n')};

export const ICONS: Record<IconName, { src: string; width: number; height: number }> = {
${names.map((n) => `  '${n}': { src: ${ident(n)}, width: ${sizes[n][0]}, height: ${sizes[n][1]} },`).join('\n')}
};
`;
fs.writeFileSync(path.join(dir, 'index.ts'), out);
console.log(`index.ts regenerated for ${names.length} icons`);
