/**
 * Regenerates src/assets/icons/index.ts from the .svg files beside it, reading each
 * one's intrinsic size from its own root attributes rather than a hand-kept list.
 */
import fs from 'node:fs';
import path from 'node:path';

const dir = path.join(import.meta.dirname, '..', 'src', 'assets', 'icons');
const names = fs.readdirSync(dir).filter((f) => f.endsWith('.svg')).map((f) => f.replace(/\.svg$/, '')).sort();
const ident = (n) => n.replace(/[^a-zA-Z0-9]/g, '_');

const sizes = Object.fromEntries(names.map((n) => {
  const svg = fs.readFileSync(path.join(dir, `${n}.svg`), 'utf8');
  const w = svg.match(/<svg[^>]*\swidth="([\d.]+)"/)?.[1];
  const h = svg.match(/<svg[^>]*\sheight="([\d.]+)"/)?.[1];
  if (!w || !h) throw new Error(`${n}.svg has no root width/height`);
  return [n, [w, h]];
}));

/* Dark copies. Each export carries its light colour baked in; the dark copy swaps
   it for the dark value of the variable that colour is bound to in the file. The
   bindings were read off every vector paint on the design page (4,637 vectors):
   each hex below is bound to the one variable named, or to two whose dark values
   agree (icon/brand and icon/selected). A glyph drawn in nothing but white is bound
   to icon/inverse. White and black inside a <mask> or <clipPath> are geometry, not
   paint, and are never touched. */
const ICON_VARIABLE = {
  '#20293c': 'Color/icon/default',
  '#2c4a8b': 'Color/icon/brand',
  '#5e6a82': 'Color/icon/subtle',
  '#9ea4b3': 'Color/icon/subtlest',
  '#038c4e': 'Color/icon/success',
  '#d42189': 'Color/icon/accent/pink',
  // Exported one step off Color/icon/danger/bolder #c1261a (MANIFEST); that variable.
  '#c2261a': 'Color/icon/danger/bolder',
};
/* Left as exported, in both themes: paints the file leaves UNBOUND, so its own Dark
   mode does not change them either (search-sm #5b6579, the receipt's socials #5a5c63,
   the pill toast's #0a9645 disc); the camera's close, already drawn in dark mode; and
   the scan line and the banner's disc, which sit on the camera and the green banner. */
const KEEP = new Set(['search-sm', 'instagram', 'facebook', 'tiktok', 'twitter', 'toast-success',
  'x-close-camera', 'scan-line', 'toast-check-card']);
const darkOf = Object.fromEntries(fs.readFileSync(path.join(dir, '..', '..', 'tokens', 'figma-variables-dark.txt'), 'utf8')
  .trim().split('\n').map((l) => l.split('|')).map(([n, , d]) => [n, d]));
const darkDir = path.join(dir, 'dark');
fs.rmSync(darkDir, { recursive: true, force: true });
fs.mkdirSync(darkDir);
const unmapped = [];
const dark = new Set();
for (const n of names) {
  if (KEEP.has(n)) continue;
  const svg = fs.readFileSync(path.join(dir, `${n}.svg`), 'utf8');
  // Geometry blocks are cut out before any paint is swapped, and put back after.
  const held = [];
  let body = svg.replace(/<(mask|clipPath)\b[\s\S]*?<\/\1>/g, (m) => `\u0000${held.push(m) - 1}\u0000`);
  const hexes = [...new Set([...body.matchAll(/(?:fill|stroke|stop-color)="(#[0-9a-fA-F]{6})"/g)].map((m) => m[1].toLowerCase()))];
  if (hexes.length === 0 && /(?:fill|stroke)="white"/.test(body)) {
    body = body.replace(/((?:fill|stroke)=)"white"/g, `$1"${darkOf['Color/icon/inverse']}"`);
  } else {
    for (const h of hexes) {
      const v = ICON_VARIABLE[h];
      if (!v || !darkOf[v]) { unmapped.push(`${n} ${h}`); continue; }
      body = body.replace(new RegExp(`="${h}"`, 'gi'), `="${darkOf[v]}"`);
    }
  }
  body = body.replace(/\u0000(\d+)\u0000/g, (_, i) => held[Number(i)]);
  if (body === svg) continue;
  fs.writeFileSync(path.join(darkDir, `${n}.svg`), body);
  dark.add(n);
}
if (unmapped.length) throw new Error(`no dark value for: ${unmapped.join(', ')}`);

const out = `/**
 * The screens' own icon exports, pulled from the Figma file itself.
 *
 * \`download_assets\` returns asset URLs on www.figma.com, which this environment's
 * network policy blocks — so these came out through the plugin API instead
 * (\`node.exportAsync({ format: 'SVG' })\`), which travels the MCP channel. Each one
 * is exported from the INSTANCE rather than the component, so it carries the colour
 * the design actually applies at that call site rather than the component's
 * uncoloured black.
 *
 * Intrinsic sizes below are read from each file's own root attributes. Do not
 * override them at a call site: the root width/height is the asset's real size, and
 * forcing a different aspect ratio distorts the glyph.
 *
 * GENERATED by scripts/gen-icons.mjs — re-run it after adding an .svg here.
 */
${names.map((n) => `import ${ident(n)} from './${n}.svg';`).join('\n')}
${[...dark].map((n) => `import ${ident(n)}_dark from './dark/${n}.svg';`).join('\n')}

export type IconName =
${names.map((n) => `  | '${n}'`).join('\n')};

/** \`dark\`: the same glyph in its bound variable's dark value (scripts/gen-icons.mjs). */
export const ICONS: Record<IconName, { src: string; dark?: string; width: number; height: number }> = {
${names.map((n) => `  '${n}': { src: ${ident(n)},${dark.has(n) ? ` dark: ${ident(n)}_dark,` : ''} width: ${sizes[n][0]}, height: ${sizes[n][1]} },`).join('\n')}
};
`;
fs.writeFileSync(path.join(dir, 'index.ts'), out);
console.log(`index.ts regenerated for ${names.length} icons, ${dark.size} with a dark copy, ${KEEP.size} kept as exported`);
